apiVersion: v1
kind: Service
metadata:
  name: randoli-tproxy
  labels:
    app.kubernetes.io/name: randoli-tproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-tproxy
spec:
  ports:
    - name: loki-proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: randoli-tproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-tproxy
  type: ClusterIP
