{{- $components := fromYaml (include "components" .) }}
{{- if $components.nodeAgent.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.nodeAgent.name }}
  labels:
    kubescape.io/ignore: "true"
subjects:
- kind: ServiceAccount
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.nodeAgent.name }}
{{- end }}
