# If prometheus enabled, add prometheus exporter
{{- if .Values.nodeAgent.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: runtime-monitor
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    app: runtime-monitor
spec:
  namespaceSelector:
    matchNames:
      -  {{ include "randoli-agent.namespace" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.nodeAgent.name }}
  endpoints:
  - port: prometheus
    path: /metrics
    scheme: http
    interval: {{ .Values.nodeAgent.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.nodeAgent.serviceMonitor.scrapeTimeout }}
{{ end }}

