apiVersion: v1
kind: Service
metadata:
  name: randoli-telemetry-proxy
  labels:
    app.kubernetes.io/name: randoli-telemetry-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-telemetry-proxy
spec:
  ports:
    - name: loki-proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: randoli-telemetry-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-telemetry-proxy
  type: ClusterIP
