{{- $netobserv := .Values.observability.netobserv | default dict }}
{{- if and (hasKey $netobserv "explodeCRs") .Values.observability.netobserv.explodeCRs }}
{{ tpl (.Files.Get "files/randoli-network/cluster-external-egress-bytes-metric.yaml") . }}
{{ end -}}