apiVersion: v2
appVersion: 1.1.0
description: Randoli App Director Agent Operator
home: https://randoli.ca
icon: https://s3.ca-central-1.amazonaws.com/randoli.ca/icons/icon-384x384.png
keywords:
- app-director
- app-director-operator
- randoli
maintainers:
- name: Randoli
  url: https://randoli.ca
  email: support@randoli.ca
name: app-director-agent-operator
sources:
- https://github.com/randoli/helm-charts
version: 1.1.0